@startuml

skinparam monochrome false
skinparam backgroundColor #EEEBDC
skinparam defaultFontColor #333333
skinparam defaultFontSize 14
skinparam defaultFontName Arial
skinparam noteFontColor #333333
skinparam noteBackgroundColor #FDF6E3
skinparam noteBorderColor #FFC107
skinparam noteBorderThickness 1.5
skinparam noteFontSize 12
skinparam sequenceArrowColor #333333
skinparam actorBorderThickness 2
skinparam actorBackgroundColor #F9A825
skinparam actorFontColor #333333
skinparam arrowThickness 1.5
skinparam shadowing true
skinparam classArrowColor #333333

actor User

User -> Wordpress: Request page
note right of Wordpress: Page generation
Wordpress -> Plugin: Retrieve components
Plugin --> Wordpress: Components
Wordpress --> User: Display page

note over User, REST_API: User interaction
User -> REST_API: Request or update data

alt Authorization is needed
REST_API -> Plugin: JWT token authorization
Plugin --> REST_API: Authorization result
alt #Pink Authorization failed
REST_API-->User: Authorization error
end
end

note right of REST_API: Retrieve data from MySQL
REST_API -> MySQL: Query data
MySQL --> REST_API: Data

REST_API --> User: Return data or status
@enduml