version: '3'

volumes:
  wordpress:
  db:

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_TABLE_PREFIX: "wp_"
    volumes:
      - wordpress:/var/www/html
      - ./deploy:/var/www/html/wp-content/plugins/


  db:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "33306:3306"
    volumes:
      - db:/var/lib/mysql