@startuml

skinparam backgroundColor #FDF6E3
skinparam usecaseBackgroundColor #FDF6E3
skinparam usecaseBorderColor #333333
skinparam usecaseBorderThickness 2
skinparam actorBackgroundColor #F9A825
skinparam actorBorderColor #333333
skinparam actorFontSize 16
skinparam actorFontColor #333333
skinparam arrowThickness 2
skinparam defaultFontName Arial
skinparam defaultFontSize 14
skinparam defaultFontColor #333333
left to right direction

actor ContentAdmin
actor QuestUser

ContentAdmin --|> (Create product)
ContentAdmin --|> (Update product)
ContentAdmin --|> (Delete product)
ContentAdmin --|> (Create service)
ContentAdmin --|> (Update service)
ContentAdmin --|> (Create calculation)
ContentAdmin --|> (Edit calculation)
ContentAdmin --|> (Delete calculation)
ContentAdmin --|> (Get statistics data)
ContentAdmin --|> (Activate/Deactivate plugin)

QuestUser --|> (Get product)
QuestUser --|> (Get service)
QuestUser --|> (Get calculation)
QuestUser --|> (Create interaction)
@enduml